import React from "react";
import ContactForm from "../../../components/SideForm/SideForm";

function CorporateTaxServices() {
  return (
    <div className="mb-28">
      <div className="bg-primary py-28 px-20 mt-10">
        <h1 className="text-white text-center text-5xl">
          Corporate Tax Services in UAE
        </h1>
      </div>
      <div className="container mx-auto">
        <div className="grid grid-cols-3">
          <div className="col-span-3 lg:col-span-2 px-10 mt-10">
            <div>
              <h1 className="text-primary text-4xl my-10">
                Federal Corporate Tax
              </h1>
              <p>
                Being a key business center point in the middle east, UAE gives
                huge tax reductions to capitalists. Extraordinary tax reductions
                are given to offer extra help to organizations get set up in
                UAE-free zones. Recently, UAE’s ministry of finance declared the
                commencement of federal corporate tax on January 31, 2022,
                scheduled to influence organizations’ monetary periods beginning
                on or after June 1, 2023. The UAE Corporate Tax framework
                complies with worldwide accepted procedures and rules given by
                OECD so the compliance cost and complexity on organizations can
                be limited.
              </p>
            </div>
            <div>
              <h1 className="text-primary text-3xl my-10">Taxable Income</h1>
              <p>
                UAE Corporate Tax is a type of direct tax on the net profit or
                loss of corporations and different organizations. Federal
                corporate tax will be rated at 9% for taxable income above AED
                375,000 and 0% for income below this threshold. Keeping this
                regime in light, going ahead licensees working in UAE will be
                expected to survey the effect of the impending regulations on
                their businesses and implement the compliance. On this matter,
                the UAE Tax Authorities have previously expressed that
                resistance to comply with corporate tax will draw high paces of
                penalties.
              </p>
            </div>
            <div>
              <h1 className="text-primary text-3xl my-10">
                Corporate Tax Applicability
              </h1>
              <p>
                Clarity has been provided by the authorities regarding the
                income of a natural person, that it will not be taxed side by
                side. Hence, income earned by UAE residents and non-residents
                does not fall in the span of the UAE Corporate Tax regime. But
                there are certain individual activities on which corporate tax
                services will be applicable such as an individual’s business
                income earned under a commercial license and any income
                generated by activities that require a permit or a license as a
                legal requirement.
                <br />
                <br />
                UAE Corporate Tax will however be applicable to all UAE
                companies and all individuals incorporated in UAE, when it comes
                to foreign legal entities, corporate tax is applicable if they
                have a permanent place of business or earnings sourced in UAE.
              </p>
            </div>
            <div>
              <h1 className="text-primary text-3xl my-10">
                Exemptions from Corporate Tax
              </h1>
              <p>
                Federal Corporate Tax regime intends to spare certain
                individuals from the applicability, so naturally, income
                generated by these individuals, specified below, will be exempt
                from corporate tax:
              </p>
              <br />
              <ul className="list-disc ml-3">
                <li>Government and government-owned entities</li>
                <li>Investment funds</li>
                <li>Businesses endeavoring and exploiting natural resources</li>
                <li>
                  Charities and further public interest organizations listed in
                  a Cabinet Decision
                </li>
              </ul>
              <br />
              <p>
                There are further exemption criteria of the above-mentioned
                specifications but in the gist of it all, federal and UAE
                government departments and entirely government-owned entities
                are accordingly exempted from corporate tax services. Other
                entities need to apply for exemption and can benefit from it
                only once it has been granted.
              </p>
            </div>
            <div>
              <h1 className="text-primary text-xl my-5">Taxable Period</h1>
              <p>
                The starting point of the Corporate Tax regime is set out to be
                accounting net profit or loss of a business as stated in the
                financial statements to lower the compliance cost. The
                utilization of accounting standards provides a common ground for
                the applicability of Corporate Tax and brings forward a
                foundation for a regime that follows international standards.
                Lining up the calculation of taxable income with accounting net
                profit or loss prevents businesses from having to maintain two
                different sets of records for the respective purposes.
                <br />
                <br />
                It is vital to ensure that businesses are preparing their
                financial statements as per standards acceptable in UAE and
                their financial accounting period will be considered their
                annual tax period, absence of formed will result in the
                Gregorian calendar becoming the annual taxing period for
                corporate tax. Small businesses and startups are being
                accommodated as well, by giving acceptance room for alternate
                financial reporting standards other than UAE-accepted IFRS.
              </p>
            </div>
            <div>
              <h1 className="text-primary text-xl my-5">Free Zones</h1>
              <p className="">
                One of the principal factors for the vision of attracting
                foreign investments for UAE has been Freezones. Consideration
                will be offered regarding the existing tax incentives in Free
                Zones to businesses complying with all the obligations, however,
                all the entities falling under Free Zones are held liable for
                Corporate Tax regime and tax return filing obligations.
                <br />
                <br />
                Keeping in light the initial motive behind Free Zones, a Free
                Zone company can still benefit from 0% Corporate tax rate if the
                income earned is from transactions originating outside the UAE
                or transactions between two free zone companies. Furthermore,
                Freezone company having an office in mainland UAE will be
                experiencing normal corporate tax rates on income generated from
                there and will enjoy 0% on its other income.
              </p>
            </div>
            <div>
              <h1 className="text-primary text-xl my-5">
                Preparing Documents for Corporate Tax
              </h1>
              <p className="">
                Documents submitted with the FTA and other financial records
                that elaborate the information restrained in the corporate tax
                return need to be maintained by the businesses. Entities exempt
                from the corporate tax services are still required to maintain
                the records for FTA to determine their exempt status. Applicable
                company laws and regulations will still determine if a business
                needs to get its financial documents audited by an attributed
                auditor. However, if a free zone company needs to avail of the
                0% corporate tax services, they are required to have audited
                financial statements.
              </p>
            </div>
          </div>
          <div className="col-span-3 lg:col-span-1 px-10 mt-10">
            <div className="bg-primary">
              <ContactForm />
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

export default CorporateTaxServices;
